[versions]
agp = "8.13.2"
androidx-activityCompose = "1.12.2"
androidx-ui-tooling = "1.10.0"
coil = "3.2.0"
compose-multiplatform = "1.9.3"
exposedBom = "1.0.0-rc-4"
flywayCore = "10.15.0"
flywayDatabasePostgresql = "10.15.0"
hikaricp = "5.1.0"
koin = "4.1.0"
kotlin = "2.3.0"
kotlinxDatetime = "0.7.1"
ktor = "3.3.3"
logbackClassic = "1.4.11"
materialIconsCore = "1.7.3"
navigationCompose = "2.9.1"
lifecycleCompose = "2.9.6"
appcompat = "1.7.1"
coreKtx = "1.17.0"
postgresql = "42.7.1"
vico = "2.3.6"
koala = "0.10.4"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-ui-tooling" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
exposed-bom = { module = "org.jetbrains.exposed:exposed-bom", version.ref = "exposedBom" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flywayDatabasePostgresql" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flywayCore" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-kotlinx-json-jvm = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktor-server-content-negotiation-jvm = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cors-jvm = { module = "io.ktor:ktor-server-cors-jvm", version.ref = "ktor" }
ktor-server-netty-jvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-status-pages-jvm = { module = "io.ktor:ktor-server-status-pages-jvm", version.ref = "ktor" }
ktor-server-request-validation-jvm = { module = "io.ktor:ktor-server-request-validation-jvm", version.ref = "ktor" }
lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleCompose" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCore" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
koala-core = { group = "io.github.koalaplot", name = "koalaplot-core", version.ref = "koala" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
